# Generated by Django 2.2.28 on 2025-02-14 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20250214_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='visits',
            new_name='views',
        ),
    ]
